#!/usr/bin/env bash
#
# Jacob Vallejo
# November 2013
#
# Login to docker image with 22 exposed to random port, this grabs the
# port, and then ssh's into it via localhost.
# 

if [ $# -lt 1 ]; then
    echo "Provide the service you want to login to."
    echo "USAGE: $0 service_name"
    echo "note: this will log into the first container it finds running."
    exit 1
fi

if [ `id -u` -ne 0 ]; then
    echo "You must be root to utilize this tool, we need to check with docker."
    exit 2
fi


user=cloud
port=$(docker ps | grep -vi ghost | grep $1 | perl -wlne 'print $1 if /(\d+)(?=->22)/')

ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $user@localhost -p $port
